name: Build Android and iOS
on:
  push:
    branches:
      - '*'
  workflow_dispatch: 
  
jobs:
install-and-test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Run tests
        run: |
          npm test
          
build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      
      - name: Install npm dependencies
        run: |
          npm install

      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease 
            - name: test before Upload

      - name: Test before upload 
        run: |
          yarn test 

      - name: Upload APK to BrowserStack
        uses: shreyanshp/upload-app-browserstack@v3
        with:
        app-path: android/app/build/outputs/apk/release/
        browserstack-username: ${{ secrets.BROWSERSTACK_USERNAME }}
        browserstack-accesskey: ${{ secrets.BROWSERSTACK_ACCESSKEY }}

build-ios:
    needs: install-and-test
    runs-on: [self-hosted, macos]
    steps: 
      - uses: actions/checkout@v2

      - name: Install npm dependencies
        run: |
          npm install

      - name: Install pod dependencies
        run: |
          cd ios && pod install

      - name: Build app
        run: |       
          xcodebuild -workspace myapp.xcworkspace -scheme myapp archive -archivePath myapp.xcarchive -allowProvisioningUpdates
          xcodebuild -exportArchive -archivePath ./myapp.xcarchive -exportPath . -exportOptionsPlist myapp/Info.plist
          mv myapp.ipa ../myapp.ipa

      - name: test before Upload
        run: |
          yarn test 

      - name: Upload IOS application to BrowserStack
        uses: shreyanshp/upload-app-browserstack@v3
        with:
        app-path: ios/build/
        browserstack-username: ${{ secrets.BROWSERSTACK_USERNAME }}
        browserstack-accesskey: ${{ secrets.BROWSERSTACK_ACCESSKEY }}
