name: CI

on:
  push:
    branches:
      - 'dev'
      - 'preprod'
      - 'prod'

  pull_request:
    branches:
      - 'dev'
      - 'preprod'
      - 'prod'

  workflow_dispatch:

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
      - run: rm package.json package-lock.json
      - run: npm init -y
      - run: npm install -D prettier @trivago/prettier-plugin-sort-imports@^4.3.0
      - run: prettier --check "app/**/*.{js,ts,tsx}" "./**/*.{yml,yaml}"
