name: CI

on:
  push:
    branches:
      - 'dev'
      - 'preprod'
      - 'staging'
      - 'prod'

  pull_request:
    branches:
      - 'dev'
      - 'staging'
      - 'preprod'
      - 'prod'

  workflow_dispatch:

jobs:
  test ios app:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Install dependencies
        run: |
          npm install --force
          npm install --location=global react-native-cli

      - name: Run unit tests
        run: npm run test

      - name: Build release app for ios
        run: npm run build:ios:release:e2e

      - run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install applesimutils
        run: |
          brew tap wix/brew
          brew install applesimutils

      - name: Run end to end tests
        run: npm run test:ios:release:e2e

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  test android app:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

    - name: Install dependencies
      run: |
        npm install --force
        npm install --location=global react-native-cli

    - name: Build release app for android
      run: npm run build:android:release:e2e

    - name: Run end to end tests
      run: npm run test:android:release:e2e

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17.x

      - run: npm install --location=global prettier
      - run: prettier --check "app/**/*.{js,ts,tsx}" "./**/*.{json,yml,yaml}"
