name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  CI:
      runs-on: macos-latest
      timeout-minutes: 15
      steps: 
        - uses: actions/checkout@v2
        - run: npm install --force
        - name: Lauch  iOS Simulator
          uses: futureware-tech/simulator-action@v1
          with: 
            model: 'iPhone 13'
            shutdown_after_job: true
        - run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      
        - name: Install applesimutils
          run: |
              brew tap wix/brew
              brew install applesimutils
        - run: npm run ci:test:e2e

