name: CI

on:
  push:
    branches:
      - 'dev'
      - 'preprod'
      - 'prod'

  pull_request:
    branches:
      - 'dev'
      - 'preprod'
      - 'prod'

  workflow_dispatch:

jobs:
  test-ios-app:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install --force
          npm install --location=global react-native-cli

      - name: Build release app for ios
        run: npm run build:ios:release:e2e

      - run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install applesimutils
        run: |
          brew tap wix/brew
          brew install applesimutils

      - name: Run end to end tests
        run: npm run test:ios:release:e2e

  test-android-app:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install --force
          npm install --location=global react-native-cli

      - name: Build release app for android
        run: npm run build:android:release:e2e

      - name: Run end to end tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          target: default
          arch: x86
          emulator-build: 6110076
          profile: Pixel 5
          avd-name: Pixel_5_API_31
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: npm run test:android:release:e2e

  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17.x

      - run: npm install --location=global prettier
      - run: prettier --check "app/**/*.{js,ts,tsx}" "./**/*.{json,yml,yaml}"
