name: CI

on:
  push:
    branches:
      - 'dev'
      - 'preprod'
      - 'prod'

  pull_request:
    branches:
      - 'dev'
      - 'preprod'
      - 'prod'

  workflow_dispatch:

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17.x

      - run: npm install --location=global prettier
      - run: prettier --check "app/**/*.{js,ts,tsx}" "./**/*.{json,yml,yaml}"
