name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  CI:
      runs-on: macos-latest
      steps: 
        - uses: actions/checkout@v2
        - run: npm install --force
        - run: npm run ci:test:e2e

