
name: browserstack-deploy
on:
  workflow_dispatch: 
  
jobs:
  build-ios: 
    runs-on: macos-latest
    timeout-minutes: 60
    steps: 
      - uses: actions/checkout@v2

      - run: npm install --force

      - run:  npm install --location=global react-native-cli
      
      - run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      
      - name: Install applesimutils
        run: |
            brew tap wix/brew
            brew install applesimutils

      - run: react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios
      
      - name: Clean project
        working-directory: ios
        run: xcodebuild clean -workspace BpartnersMobile.xcworkspace -scheme BpartnersMobile

      - working-directory: ios
        run: xcodebuild -list

      - working-directory: ios
        run:  xcodebuild archive -project BpartnersMobile.xcodeproj -scheme BpartnersMobile.xschemes -archivePath BpartnersMobile.xcarchive -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      - working-directory: ios
        run: xcodebuild -exportArchive -exportFormat ipa  -archivePath BpartnersMobile.xcarchive -exportPath BpartnersMobile 

      - run: cd ios && pod install

      - run: npm run ci:build:e2e
      
      - run: npm run ci:test:e2e 
      
      - run: curl -u "${{ secrets.BROWSERSTACK_USERNAME }}:${{ secrets.BROWSERSTACK_ACCESSKEY }}" -X POST "https://api-cloud.browserstack.com/app-live/upload" -F "file=@ios/build/myapp.ipa"

